repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-white-space
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
